### ISSUE TITLE
Preferences and Stram Setting - doesn't save

### ISSUE THREAD

**Issue by oester** [mmcc-xx/BirdCAGE#1]
I have it up and running but when I go to the Preference or Stream Settings, I enter in the information and hit save - nothing happens. And I don't see a way to navigate back to the main page. I go to Preferences or Streams - data I entered is not saved.

**Comment by mmcc-xx** [comment]
I haven’t put nav buttons on the preferences or streams pages yet. Try going to the api server url in your browser - a ui for testing the apis should come up. Does it?

**Comment by oester** [comment]
What url is that?

**Comment by mmcc-xx** [comment]
In the docker compose file you would have set an environment variable for birdcage_front end called API_SERVER_URL telling it the url of birdcage_backend. Since my server’s ip address is 192.168.1.75, and I have the backend exposed on port 7007, the url is http://192.168.1.75:7007

Since all of the api requests are done in client side JavaScript to keep things snappy, both the front end and back end urls need to be accessible from your browser.

**Comment by fightforlife** [comment]
Have the same issue, stream save button does nothing.
Frontend and backend are accessible via browser.

**Comment by oester** [comment]
> In the docker compose file you would have set an environment variable for birdcage_front end called API_SERVER_URL telling it the url of birdcage_backend. Since my server’s ip address is 192.168.1.75, and I have the backend exposed on port 7007, the url is http://192.168.1.75:7007
> 
> Since all of the api requests are done in client side JavaScript to keep things snappy, both the front end and back end urls need to be accessible from your browser.

Yes, I can get to that (In my case 192.168.15.207:7007)

**Comment by oester** [comment]
I figured out the issue - I had missed one of the IP addresses that were hard coded to 1.75. Restarted as indicated, and I do see some detects!
