### ISSUE TITLE
Analyzer Container won't start: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by yetdog** [mmcc-xx/BirdCAGE#13]
Have followed the instructions to get your modified BirdNET-Analyzer up and running, built the container. Then:

```
[root@homedocker1 BirdNET-Analyzer]# docker-compose up 
birdnet-analyzer_birdnetserver_1 is up-to-date
Attaching to birdnet-analyzer_birdnetserver_1
birdnetserver_1  | Traceback (most recent call last):
birdnetserver_1  |   File "server.py", line 12, in <module>
birdnetserver_1  |     import config as cfg
birdnetserver_1  |   File "/config.py", line 115, in <module>
birdnetserver_1  |     LABELS: list[str] = []
birdnetserver_1  | TypeError: 'type' object is not subscriptable
birdnetserver_1  | Traceback (most recent call last):
birdnetserver_1  |   File "server.py", line 12, in <module>
birdnetserver_1  |     import config as cfg
birdnetserver_1  |   File "/config.py", line 115, in <module>
birdnetserver_1  |     LABELS: list[str] = []
birdnetserver_1  | TypeError: 'type' object is not subscriptable
birdnetserver_1  | Traceback (most recent call last):
birdnetserver_1  |   File "server.py", line 12, in <module>
birdnetserver_1  |     import config as cfg
birdnetserver_1  |   File "/config.py", line 115, in <module>
birdnetserver_1  |     LABELS: list[str] = []
birdnetserver_1  | TypeError: 'type' object is not subscriptable
birdnet-analyzer_birdnetserver_1 exited with code 1
```

**Comment by Phaeton** [comment]
I saw this error yesterday. Make sure you pull the latest `analyze.py` and `server.py` from the [repo](https://github.com/mmcc-xx/BirdCAGE/tree/main/BirdNET-Analyzer) and then rebuild the birdnetserver container.

**Comment by yetdog** [comment]
> repo

Yep, I grabbed them minutes ago, so can't imagine my files were out of date.

Not sure if my workaround causes an issue or not. Currently chasing down an error where ffmpeg reports out of space on device (not remotely true).

**Comment by mmcc-xx** [comment]
Huh - that is odd. I'm going to push my own analyzer image later today everything can be lumped into one docker-compose and we can be reasonably sure everything will work today. I'm no expert at docker technologies unfortunately and have been tending to push image updates pretty regularly, but I try to make sure they work when I do :)

**Comment by yetdog** [comment]
Thanks! Now that I'm down to the singular issue of the analyzer not running (not being called / connected to?), this is the only change I made that deviated from the instructions so of course it has me nervous that I've somehow blown it up. :)

Appreciate all your efforts - have been hoping for a project like this for a while, but a toddler means no time to code myself. Can certainly help t-shoot tho!

**Comment by mmcc-xx** [comment]
OK - please take a look at the new docker-compose file. I pushed an analyzer image that _should_ work fine.

Kids are the worst :) Mine are now old enough that I have some time to do stuff.

**Comment by brucewinter** [comment]
I had the same not subscriptable TypeError with the previous code (Analyzer installed directly from BirdNet).   Following the latest README instructions, I simply copied and update the docker-compose.yml file into an empty dir, created .db and .detections dirs, and did 'docker-compose up'.  Docker shows all 3 birdcage-* containers running :)   However ...

I am getting no detections.  Pretty sure my streams are ok.   I get this error on the birdnetserver url  localhost:7667 

Sorry, the requested URL 'http://localhost:7667/' caused an error:
Not found: '/'

The docker log shows:

UP AND RUNNING! LISTENING ON 0.0.0.0:8080

The only thing I changed in the compose file was the 3 ..1.71 strings to my ip address.   

More log data attached.  Any suggestions on how to debug?

------------

bruce@nuc7:~/apps/BirdCAGE$ sudo docker-compose up
[+] Running 4/0
 ?? Container birdcage-birdnetserver-1      Created                                                                                                                                                                                                                                                     0.0s 
 ?? Container birdcage-redis-1              Created                                                                                                                                                                                                                                                     0.0s 
 ?? Container birdcage-birdcage_backend-1   Created                                                                                                                                                                                                                                                     0.0s 
 ?? Container birdcage-birdcage_frontend-1  Created                                                                                                                                                                                                                                                     0.0s 
Attaching to birdcage-birdcage_backend-1, birdcage-birdcage_frontend-1, birdcage-birdnetserver-1, birdcage-redis-1
birdcage-redis-1              | 1:C 24 May 2023 18:00:44.775 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
birdcage-redis-1              | 1:C 24 May 2023 18:00:44.783 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
birdcage-redis-1              | 1:C 24 May 2023 18:00:44.783 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.784 * monotonic clock: POSIX clock_gettime
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.784 * Running mode=standalone, port=6379.
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.784 # Server initialized
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.784 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.785 * Loading RDB produced by version 7.0.11
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.785 * RDB age 294 seconds
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.785 * RDB memory usage when created 0.82 Mb
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.785 * Done loading RDB, keys loaded: 0, keys expired: 0.
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.785 * DB loaded from disk: 0.000 seconds
birdcage-redis-1              | 1:M 24 May 2023 18:00:44.785 * Ready to accept connections
birdcage-birdnetserver-1      | UP AND RUNNING! LISTENING ON 0.0.0.0:8080
birdcage-birdcage_backend-1   | Starting API Server
birdcage-birdcage_backend-1   | Starting celery_worker
birdcage-birdcage_backend-1   | Sleeping indefinitely
birdcage-birdcage_backend-1   | [2023-05-24 13:00:45 -0500] [7] [INFO] Starting gunicorn 20.1.0
birdcage-birdcage_backend-1   | [2023-05-24 13:00:45 -0500] [7] [INFO] Listening at: http://0.0.0.0:7007 (7)
birdcage-birdcage_backend-1   | [2023-05-24 13:00:45 -0500] [7] [INFO] Using worker: sync
birdcage-birdcage_backend-1   | [2023-05-24 13:00:45 -0500] [18] [INFO] Booting worker with pid: 18
birdcage-birdcage_frontend-1  | [2023-05-24 13:00:46 -0500] [7] [INFO] Starting gunicorn 20.1.0
birdcage-birdcage_frontend-1  | [2023-05-24 13:00:46 -0500] [7] [INFO] Listening at: http://0.0.0.0:7008 (7)
birdcage-birdcage_frontend-1  | [2023-05-24 13:00:46 -0500] [7] [INFO] Using worker: sync
birdcage-birdcage_frontend-1  | [2023-05-24 13:00:46 -0500] [8] [INFO] Booting worker with pid: 8
birdcage-birdcage_backend-1   | Starting celery worker in celery_worker.py
birdcage-birdcage_backend-1   | here's data in count_by_hour:
birdcage-birdcage_backend-1   | []
birdcage-birdcage_backend-1   | here's data in count_by_hour:
birdcage-birdcage_backend-1   | []

**Comment by brucewinter** [comment]
Thanks for the debug suggestions!   Everything looks good until I try to create stream, where I now get this message: 

  Error creating stream: undefined

Yesterday, with the same input parms, that step worked and I had a stream listed just like you showed.    vlc on the same address (rtsp://192.168.86.152:8554/c9_sub) works fine, audio plays plenty of bird sounds.   I didn't see anything fishy in any of the 4 docker logs (can post those if useful). 

Seems you fixed the TypeError issue, let me know if you want me to open a new issue.  Thanks for the help!

**Comment by brucewinter** [comment]
A fresh install did the trick!!

I see some changes to the front end (e.g. Settings is now a pulldown menu) and I am now seeing what looks like good errata.  For example:

birdcage-birdnetserver-1      | ####################  2023-05-25 19:34:46.737733  ####################
birdcage-birdnetserver-1      | {'lat': '33.44', 'lon': '-86.38', 'week': 21, 'overlap': '0', 'sensitivity': '1.5', 'sf_thresh': '0.01', 'pmode': 'max', 'num_results': 5, 'save': False}
birdcage-birdnetserver-1      | Analyzing /tmp/tmpgvwl9iwi.wav
birdcage-birdnetserver-1      | Finished /tmp/tmpgvwl9iwi.wav in 0.59 seconds
birdcage-birdnetserver-1      | Results:
birdcage-birdnetserver-1      | {'12.0;15.0': [('Cardinalis cardinalis_Northern Cardinal', 0.5826), ('Mimus polyglottos_Northern Mockingbird', 0.1312), ('Thryothorus ludovicianus_Carolina Wren', 0.1083), ('Passer domesticus_House Sparrow', 0.0991), ("Limnothlypis swainsonii_Swainson's Warbler", 0.0898)]}
birdcage-birdcage_backend-1   | [2023-05-25 14:35:02,381: WARNING/ForkPoolWorker-6] Recording successful. File saved to: /app/../tmp/7b3a47817fad4e60a789bd9c9898a10e.wav
birdcage-birdcage_backend-1   | [2023-05-25 14:35:02,412: WARNING/ForkPoolWorker-7] Requesting analysis for /app/../tmp/7b3a47817fad4e60a789bd9c9898a10e.wav
 
My only remaining issue I don't see any entries in the detection page.  Should I be playing with the filters, or would you expect I would have detections listed for the above Cardinal example with the defaults?

**Comment by mmcc-xx** [comment]
Excellent! Glad to hear.  The number after the species is the confidence. The default threshold for call it a match is 0.7. Since none of these are above that level you wouldn't see any detections.

```
[('Cardinalis cardinalis_Northern Cardinal', 0.5826), ('Mimus polyglottos_Northern Mockingbird', 0.1312), ('Thryothorus ludovicianus_Carolina Wren', 0.1083), ('Passer domesticus_House Sparrow', 0.0991), ("Limnothlypis swainsonii_Swainson's Warbler", 0.0898)]
```

**Comment by mmcc-xx** [comment]
You're getting a lot of action but probably a lot of false positives. 

I'm glad you are enjoying it!
